FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir rapidocr onnxruntime pillow-heif

COPY ocr_test.py .

ENTRYPOINT ["python", "ocr_test.py"]